if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold "${Esc}[1m")
  set(Red "${Esc}[31m")
  set(Green "${Esc}[32m")
  set(Yellow "${Esc}[33m")
  set(Blue "${Esc}[34m")
  set(Magenta "${Esc}[35m")
  set(Cyan "${Esc}[36m")
  set(White "${Esc}[37m")
  set(BoldRed "${Esc}[1;31m")
  set(BoldGreen "${Esc}[1;32m")
  set(BoldYellow "${Esc}[1;33m")
  set(BoldBlue "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan "${Esc}[1;36m")
  set(BoldWhite "${Esc}[1;37m")
endif()

function(LogTrace msg)
  message("${ColourBold} [STATUS] ${ColourReset} ${msg}")
endfunction(LogTrace)

function(LogDebug msg)
  message("${Cyan} [DEBUG] ${ColourReset} ${msg}")
endfunction(LogDebug)

function(LogInfo msg)
  message("${Green} [INFO] ${ColourReset} ${msg}")
endfunction(LogInfo)

function(LogWarn msg)
  message("${BoldYellow} [WARNING] ${ColourReset} ${msg}")
endfunction(LogWarn)

function(LogError msg)
  message(SEND_ERROR "${BoldRed} [ERROR] ${ColourReset} ${msg}")
endfunction(LogError)

function(LogFatal msg)
  message(FATAL_ERROR "${BoldRed} [FATAL] ${ColourReset} ${msg} ")
endfunction(LogFatal)
